### PR TITLE
Add button to copy text

### LINKED ISSUE #9: add button to copy text
Consider using a clipboard library https://clipboardjs.com/

For example the copy button in this photo:
Screen Shot 2019-10-05 at 9 30 57 PM

Given 
I click to generate lorem ipsum
generated text appears
I can click a button to copy all of the generated text into clipboard

### PR DESCRIPTION
**Pull request by AngelFQC**
Fix #9

### CODE REVIEW

**Comment by AngelFQC** [comment]
Please, ~~merge~~ review #10 to fix a warning and then ~~merge~~ review this :smile:

**Comment by M0nica** [comment]
Hi @AngelFQC. Thanks for working on this issue. Can you resolve the merge conflicts? Also, It would be ideal for one button to copy all of the text and not just individual paragraphs.

**Comment by AngelFQC** [comment]
I will

**Comment by AngelFQC** [comment]
Hi @M0nica 
Done :)

**Comment by M0nica** [comment]
Thank you for this contribution!

**Pull request merged**
